<?php
/**
 * This file is part of Onion
 *
 * Copyright (c) 2014-2016, Humberto Lourenço <betto@m3uzz.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Humberto Lourenço nor the names of his
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @category   PHP
 * @package    Onion
 * @author     Humberto Lourenço <betto@m3uzz.com>
 * @copyright  2014-2016 Humberto Lourenço <betto@m3uzz.com>
 * @license    http://www.opensource.org/licenses/BSD-3-Clause  The BSD 3-Clause License
 * @link       http://github.com/m3uzz/onionfw
 */
 
if (!empty($gsIcon))
{
	$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath($gsIcon)));
}

if (isset($gaMeta['admCSS']) && !empty($gaMeta['admCSS']))
{
	$this->headLink()->prependStylesheet($this->basePath($gaMeta['admCSS']), 'all');
}

$this->headLink()
	->prependStylesheet($this->basePath('/vendor/lumino/css/print.css'), 'print')
	->prependStylesheet($this->basePath('/vendor/lumino/css/media.css'), 'all')
	->prependStylesheet($this->basePath('/vendor/onion/css/style.css'), 'all')
	->prependStylesheet($this->basePath('/vendor/jquery-ui-1.11.2/jquery-ui.min.css'), 'all')
	->prependStylesheet($this->basePath('/vendor/bootstrap-3.3.4/css/bootstrap-theme.min.css'), 'all')
	->prependStylesheet($this->basePath('/vendor/bootstrap-3.3.4/css/bootstrap.min.css'), 'all');

$this->headScript()
  	->prependFile($this->basePath('/vendor/onion/js/common.js'))
  	->prependFile($this->basePath('/vendor/onion/js/popup.js'))
   	->prependFile($this->basePath('/vendor/bootstrap-3.3.4/js/bootstrap.min.js'))
   	->prependFile($this->basePath('/vendor/jquery-ui-1.11.2/jquery-ui.min.js'))
    ->prependFile($this->basePath('/vendor/jquery-1.11.1/jquery.min.js'))
    ->prependFile($this->basePath('/vendor/onion/js/loadfile.js'))
    ->prependFile($this->basePath('/vendor/onion/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('/vendor/onion/js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
?>
    <head>
        <meta charset="<?php echo $gaMeta['charset']?>">
        
        <?php 
        echo $this->headTitle($gaMeta['siteTitle'])
        	->setSeparator($gaMeta['titleSeparator'])
        	->setAutoEscape(false); 

        echo $this->headMeta()
            ->appendName('viewport', $gaMeta['viewport'])
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink();
        
        echo $this->headScript(); 
        ?>
        
		<script type="text/javascript">
			var OnionDebugJs = <?php echo ($gbDebugJs ? 'true' : 'false'); ?>;
		</script>
    </head>