            <div id="ajaxSimpleModal" class="modal fade bs-example-modal-lg hidden-print" tabindex="-1" role="dialog" aria-labelledby="ajaxSimpleModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
			    	<div class="modal-content">
			      		<div class="modal-header">
			        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			        		<h4 class="modal-title" id="ajaxSimpleModalLabel"></h4>
			      		</div>
			      		<div class="modal-body">
							Carregando ...
			      		</div>
			      		<div class="modal-footer">
			        		<button id="ajaxSimpleModalCancelBtn" type="button" class="btn btn-default ajaxSimpleModalCancelBtn" data-dismiss="modal"><?php echo $this->translate('Cancelar'); ?></button>
			        		<button id="ajaxSimpleModalConfirmBtn" type="button" class="btn btn-primary ajaxSimpleModalConfirmBtn"><?php echo $this->translate('Ok'); ?></button>
			        	</div>
			    	</div>
			  	</div>
			</div>