        <ul class="user-menu">
			<li class="pull-right">
				&nbsp;&nbsp;
				<a id="push" href="#" role="button" data-toggle="dropdown" class="iconnav">
					<i class="glyphicon glyphicon-bell"></i>&nbsp;
					<span id="pushAlert" class="badge"></span>
				</a>
				&nbsp;&nbsp;
			</li>
        </ul>
		<div id="pushMessage"></div>
		
        <div id="pushTemplate" class="hidden-print hidden">
       		<div class="alert alert-dismissable" role="alert">
       			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  					<span aria-hidden="true">&times;</span>
				</button>
   			</div>
        </div>