<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>ERROR 500 Internal Server Error</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    </head>
    <body>
        <div class="container">
	  		<fieldset style="border:solid 1px #ff6600; background:#ffccaa; margin:50px;">
				<legend style="color:#ff6600">
					<b> Error: </b>
				</legend>
				<code>
					ERROR 500 Internal Server Error 
					<i>(<?php echo $e->getMessage(); ?>)</i>
				</code>
			</fieldset>
        </div>
    </body>
</html>