<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
		'DoctrineModule',
		'DoctrineORMModule',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './vendor/m3uzz/module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    ),
);
