		<footer class="bgcolor-2">
			<div class="container">
				
				<div class="footer-logo">
					<img src="<?php echo $gaMeta['logoSite']; ?>" alt="<?php echo $gaMeta['siteTitle']; ?>" style="width:104px;">
				</div>
				
				<div class="copyright">
					 ©<?php echo date('Y ') . $gaMeta['siteTitle']; ?>.
				</div>
				
				<ul class="social-icons">
					<li>
						<a href=""><span class="social_facebook_square"></span></a>
					</li>
					<li>
						<a href=""><span class="social_twitter_square"></span></a>
					</li>
					<li>
						<a href=""><span class="social_googleplus_square"></span></a>
					</li>
					<li>
						<a href=""><span class="social_linkedin_square"></span></a>
					</li>
				</ul>
				
			</div>
		</footer>