		<header id="home">	
			<!-- COLOR OVER IMAGE -->
			<div class="color-overlay">
				<div class="navigation-header">
				
					<?php include ('widget-menu.phtml'); ?>
					
					<!-- ONLY LOGO ON HEADER -->
					<div class="navbar non-sticky">
						<div class="container">
							<div class="navbar-header">
								<img src="<?php echo $gaMeta['logoSite']; ?>" alt="<?php echo $gaMeta['siteTitle']; ?>">
							</div>
							<ul class="nav navbar-nav navbar-right social-navigation hidden-xs">
								<li><a href="#"><i class="social_facebook_circle"></i></a></li>
								<li><a href="#"><i class="social_twitter_circle"></i></a></li>
								<li><a href="#"><i class="social_linkedin_circle"></i></a></li>
							</ul>
						</div>
						<!-- /END CONTAINER -->
					</div>
					<!-- /END ONLY LOGO ON HEADER -->
				</div>
				
				<!-- HEADING, FEATURES AND REGISTRATION FORM CONTAINER -->
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<!-- SCREENSHOT -->
							<div class="home-screenshot side-screenshot pull-left">
								<img src="vendor/m3uzz/onionjs-0.16.4/dist/front/img/screenshots/1.jpg" alt="Feature" class="img-responsive">
							</div>
						</div>
						
						<!-- RIGHT - HEADING AND TEXTS -->
						<div class="col-md-6 intro-section">
							
							<h1 class="intro text-left">
							Get the Best <span class="strong colored-text">Solution</span> for Your <strong>Business</strong>
							</h1>
							
							<p class="sub-heading text-left">
							    Tablet publishing HTML5 mobile first really simple syndication meetups white board walls. User experience iterate algorithm gamification semantic web value add market research stealth. Rockstar developer internet of things bleeding edge.
							</p>
							
							<!-- CTA BUTTONS -->
							<div id="cta-5" class="button-container">
								<a href="#" class="btn standard-button pull-left">Get Started</a>
								<a href="/backend" class="btn secondary-button-white pull-left">Login</a>
							</div>
						</div>
					</div>
				</div>
				<!-- /END HEADING, FEATURES AND REGISTRATION FORM CONTAINER -->
				
			</div>
		
		</header>