<?php
/**
 * This file is part of Onion
 *
 * Copyright (c) 2014-2016, Humberto Lourenço <betto@m3uzz.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   * Neither the name of Humberto Lourenço nor the names of his
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @category   PHP
 * @package    Onion
 * @author     Humberto Lourenço <betto@m3uzz.com>
 * @copyright  2014-2016 Humberto Lourenço <betto@m3uzz.com>
 * @license    http://www.opensource.org/licenses/BSD-3-Clause  The BSD 3-Clause License
 * @link       http://github.com/m3uzz/onionfw
 */
 
$gsController = $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()->getParam('controller');
$gsAction = $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()->getParam('action');
$gaController = explode('\\', $gsController);
$gsSlug = $gaController[0] . $gaController[2] . '-' . ucFirst($gsAction);

$gaConfig = Onion\Config\Config::getAppOptions();
$gaMeta = $gaConfig['front']['meta'];
$goUser = $this->identity();
$gbDebugJs = $gaConfig['log']['debug']['JS'];
$gaService = $gaConfig['service']['facebook'][APP_ENV];

echo $this->doctype($gaMeta['doctype']);
?>
<html lang="<?php echo $gaMeta['lang']; ?>">
	<?php include ('area-head.phtml'); ?>
	
	<body id="<?php echo $gsSlug; ?>">
		<div class="preloader">
		  <div class="status">&nbsp;</div>
		</div>
		
		<?php
			if ($gsSlug == "ApplicationIndex-Index")
			{ 
				include ('area-header-home.phtml');
			}
			else 
			{
				include ('area-header-internal.phtml');
			}
		?>
		
		<?php echo $this->content; ?>
		
		<?php include ('area-footer.phtml'); ?>
		
		<script src="/vendor/jquery/jquery-1.12.3/dist/jquery.min.js"></script>
		
		<script>
			jQuery(window).load(function() {
				"use strict";
			        // will first fade out the loading animation
				jQuery(".status").fadeOut();
			        // will fade out the whole DIV that covers the website.
				jQuery(".preloader").delay(200).fadeOut("slow");
			})
		</script>
				
		<?php echo $this->inlineScript(); ?>
	</body>
</html>