				<!-- STICKY NAVIGATION -->
				<div class="navbar navbar-inverse bs-docs-nav navbar-fixed-top sticky-navigation">
					<div class="container">
						<div class="navbar-header">
							
							<!-- LOGO ON STICKY NAV BAR -->
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#landx-navigation">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							</button>
							<a class="navbar-brand" href="/#"><img src="<?php echo $gaMeta['logoSite']; ?>" alt="<?php echo $gaMeta['siteTitle']; ?>"></a>
							
						</div>
						
						<!-- NAVIGATION LINKS -->
						<div class="navbar-collapse collapse" id="landx-navigation">
							<ul class="nav navbar-nav navbar-right main-navigation">
								<li><a href="/#home">Home</a></li>
								<li><a href="/#section1">Brief</a></li>
								<li><a href="/#section3">Features</a></li>
								<li><a href="/#section4">Pricing</a></li>
								<li><a href="/#section5">Video</a></li>
								<li><a href="/#section6">Screenshots</a></li>
								<li><a href="/#section7">Testimonial</a></li>
								<li><a href="/#section8">Contact</a></li>
								<li><a href="/backend">login</a></li>
							</ul>
						</div>
						
					</div>
					<!-- /END CONTAINER -->
					
				</div>				
				<!-- /END STICKY NAVIGATION -->